### ISSUE TITLE
Failure when receiving data from the peer

### ISSUE THREAD

**Issue by MoritzKaufmann** [Bioconductor/KEGGREST#11]
Hi,

When I tried to rerun my code, which worked fine a few months ago, I now run into a problem. I want to fetch a simple kegglist. 

pathways.list = keggList('pathway','ath')

However I allways get the error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer

Thank you very much for your help. 
Moritz

**Comment by lshep** [comment]
Questions like this are better asked on the [Bioconductor support site](https://support.bioconductor.org/) so the community can also answer. 
I cannot reproduce this 
```
> library(KEGGREST)
>  pathways.list = keggList('pathway','ath')
h> head(pathways.list)
                                                                  path:ath00010 
            "Glycolysis / Gluconeogenesis - Arabidopsis thaliana (thale cress)" 
                                                                  path:ath00020 
               "Citrate cycle (TCA cycle) - Arabidopsis thaliana (thale cress)" 
                                                                  path:ath00030 
               "Pentose phosphate pathway - Arabidopsis thaliana (thale cress)" 
                                                                  path:ath00040 
"Pentose and glucuronate interconversions - Arabidopsis thaliana (thale cress)" 
                                                                  path:ath00051 
         "Fructose and mannose metabolism - Arabidopsis thaliana (thale cress)" 
                                                                  path:ath00052 
                    "Galactose metabolism - Arabidopsis thaliana (thale cress)" 
> 

```

There were recent updates to endpoints so please make sure you are using the most recent version of the package for your version of R / Bioc: version  1.36.2 for Bioc release 3.15 or  1.37.2 for Bioc devel 3.16

**Comment by lshep** [comment]
If you continue to have issues and post on the support site,  please remember to include your `sessionInfo()` from R that will include your R version, package versions, and OS information.

**Comment by MoritzKaufmann** [comment]
Dear Ishep,

Thank you so much for the fast response. It was indeed just a versioning error. 

Thank you again. 
Moritz
