### ISSUE TITLE
keggLink() returns error

### ISSUE THREAD

**Issue by ValePalo** [Bioconductor/KEGGREST#14]
Hello,
Thanks for your amazing package!
Lately, when I try to use keggLink()  I get the following error:

_Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer_

I'd appreciate any help on the issue,
Best,
-V

**Comment by lshep** [comment]
Are you using the latest versions of the package?  `sessionInfo()` ?   This was reported previously at [Issue 7](https://github.com/Bioconductor/KEGGREST/issues/7) and seemed fixed with the added [PR 8](https://github.com/Bioconductor/KEGGREST/pull/8) that was already merged?

**Comment by ValePalo** [comment]
Thank you for your help!
I have installed new R and KEGGREST version and keggLink() function works properly now.
