### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by powerhorse1986** [Bioconductor/KEGGREST#17]
Hi, 

I was trying to pull the gene information of a given KEGG pathway id using keggGet(). However, an error prompted as the following:

Error in curl::curl_fetch_memory(url, handle = handle) :
SSL peer certificate or SSH remote key was not OK: [rest.kegg.jp] SSL certificate problem: certificate has expired

Would you please help fixing the bug?

Thanks
Li

**Comment by Magetutor** [comment]
I encountered the same error. When I run the keggLink(), the error was occured as following: 

_Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - 收到的证书已过期。_

**Comment by lshep** [comment]
what version of R/Bioc and KEGGREST are you using?  Can you please provide your `sessionInfo()`

**Comment by powerhorse1986** [comment]
Hi Ishep,

Thanks for your response. There's no more problem any more. It seemed like it's the problem of KEGG, but not KEGGREST.

Thanks again.

Li
